---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: "ProjectMonitoringTool"
  contact: {
    email: "chocolateironman98@gmail.com"
  }
#host: "projectmt.herokuapp.com"
host: localhost:8080
schemes:
#- "https"
- 'http'
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /project:
    get:
      tags:
      - "Project"
      summary: "Loads a list of projects"
      operationId: "getProjects"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Project"
        400:
          description: "Status 400"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Project"
    post:
      tags:
      - "Project"
      summary: "Adds a project"
      operationId: "postProject"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "The project has been saved"
          schema:
            $ref: "#/definitions/Project"
        400:
          description: "The project already exists"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Project"
  /project/{ProjectID}:
    get:
      tags:
      - "Project"
      summary: "Loads a project"
      operationId: "getProject"
      parameters:
      - name: "ProjectID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Status 400"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Project"
    put:
      tags:
      - "Project"
      summary: "Updates a project"
      operationId: "putProject"
      parameters:
      - name: "ProjectID"
        in: "path"
        required: true
        type: "string"

      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Project"
    delete:
      tags:
      - "Project"
      summary: "Deletes a project"
      operationId: "deleteProject"
      parameters:
      - name: "ProjectID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Project"
  /tutor:
    get:
      tags:
      - "Tutor"
      summary: "Loads a list of tutors"
      operationId: "getTutors"
      produces:
      - "application/json"
      - "application/x-yaml"
      - "application/xml"
      - "text/xml"
      parameters: 
      - name: "tutorID"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tutor"
        400:
          description: "Status 400"
        
      x-swagger-router-controller: "Tutor"
    post:
      tags:
      - "Tutor"
      summary: "Adds a tutor"
      operationId: "postTutor"
      consumes:
      - "application/json"
      produces:
      - "application/json"
     
      responses:
        200:
          description: "We added the tutor"
          schema:
            $ref: "#/definitions/Tutor"
        400:
          description: "We already added the tutor"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Tutor"
  /tutor/{TutorID}:
    get:
      tags:
      - "Tutor"
      summary: "Loads a tutor"
      operationId: "getTutor"
      parameters:
      - name: "TutorID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "The tutor exist in the database"
        404:
          description: "The tutor does not match the database"
        
      x-swagger-router-controller: "Tutor"
    
    delete:
      tags:
      - "Tutor"
      summary: "Deletes a tutor"
      operationId: "deleteTutor"
      parameters:
      - name: "TutorID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Bad Request"
        
      x-swagger-router-controller: "Tutor"
  /projectCategory:
    get:
      tags:
      - "Category"
      summary: "Loads a list of project categories"
      operationId: "getCategories"
      parameters:
      - name: "name"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
        404:
          description: "Status 404"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Category"
    post:
      tags:
      - "Category"
      summary: "Adds a project category"
      operationId: "postCategory"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Category"
      responses:
        200:
          description: "The category is created"
        400:
          description: "The category already exists"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Category"
  /projectCategory/{categoryID}:
    get:
      tags:
      - "Category"
      summary: "Loads a project category"
      operationId: "getCategory"
      parameters:
      - name: "categoryID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "The category exists"
        404:
          description: "The category doesn't exist"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Category"
    delete:
      tags:
      - "Category"
      summary: "Deletes a category"
      operationId: "deleteCategory"
      parameters:
      - name: "categoryID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Category"
  /projectTasks:
    get:
      tags:
      - "Task"
      summary: "Loads a list of project tasks"
      operationId: "getTasks"
      parameters: 
        - name: "projectID"
          in: "query"
          required: true
          type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
        404:
          description: "Status 404"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Task"
    post:
      tags:
      - "Task"
      summary: "Adds a project task"
      operationId: "postTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "Task successfully created"
        400:
          description: "The task already exists"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Task"
  /projectTasks/{TaskID}:
    get:
      tags:
      - "Task"
      summary: "Loads a task"
      operationId: "getTask"
      parameters:
      - name: "TaskID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "The task is found"
        404:
          description: "The task doesn't exist"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Task"
    put:
      tags:
      - "Task"
      summary: "Stores a task"
      operationId: "putTask"
      parameters:
      - name: "TaskID"
        in: "path"
        required: true
        type: "string"
      
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Status 400"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Task"
    delete:
      tags:
      - "Task"
      summary: "Deletes a task"
      operationId: "deleteTask"
      parameters:
      - name: "TaskID"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - projectmt_admin_auth:
        - "admin"
      x-swagger-router-controller: "Task"
securityDefinitions:
  projectmt_admin_auth:
    type: "oauth2"
    authorizationUrl: "https://projectmt.eu.auth0.com/authorize"
    flow: "implicit"
    scopes:
      admin: "Full Access"
definitions:
  Project:
    type: "object"
    required:
    - "ProjectName"
    - "ProjectCategory"
    - "ProjectYear"
    - "StartDate"
    - "EndDate"
    - "GroupName"
    - "Notes"
    properties:
      ProjectName:
        type: "string"
      ProjectCategory:
        type: "string"
      ProjectYear:
        type: "integer"
      StartDate:
        type: "integer"
      EndDate:
        type: "integer"
      GroupName:
        type: "string"
      Notes:
        type: "string"
    description: "parameters needed to create a project"
    example:
      ProjectName: "name"
      ProjectCategory: "uuid"
      ProjectYear: 1
      StartDate: 123
      EndDate: 123
      GroupName: "name"
      Notes: "some notes"
  Tutor:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
    description: "Parameters required for tutor"
    example:
      id: "uuid"
      
  Category:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
    description: "parameters needed to create a category"
    example:
      name: "App"
  Task:
    type: "object"
    required:
     - "TaskName"
     - "StartDate"
     - "EndDate"
     - "DueDate"
     - "Notes"
    properties:
      TaskName:
        type: "string"
      StartDate:
        type: "integer"
      EndDate:
        type: "integer"
      DueDate:
        type: "integer"
      Notes:
        type: "string"
    description: "parameters needed to create a task"
    example:
      TaskName: "name"
      StartDate: 123
      EndDate: 123
      DueDate: 123
      Notes: "some notes"